name: Deploy backend

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "backend"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Pull changes
        run: >
          ssh staging "
            cd apps/mj &&
            git fetch &&
            git reset --hard origin/main
          "
      - name: Install dependencies and build
        run: >
          ssh staging "
            cd apps/mj &&
            npm ci &&
            npm run build
          "
      - name: Restart application
        run: ssh staging "supervisorctl restart mj"
